"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BAG_RULES } from "@/lib/packaging-bag-calculator";
import { encodeActorHeader } from "@/lib/actor-header";

function todayMyanmar() { const now = new Date(Date.now() + (6 * 60 + 30) * 60 * 1000); return `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, "0")}-${String(now.getUTCDate()).padStart(2, "0")}`; }
function formatNumber(value) { return Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 }); }
function shiftDate(value, delta) { const date = new Date(`${value}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + delta); return date.toISOString().slice(0, 10); }
function actorHeaders(headers = {}) { const actorName = typeof window !== "undefined" ? window.localStorage.getItem("actorName") || "" : ""; return { ...headers, "x-actor-name": encodeActorHeader(actorName) }; }
function movementLabel(movement) { return movement.movementType === "PRODUCTION_USE_OUT" ? "ဗူးထုတ်လုပ်ရာတွင် သုံးစွဲ" : "Stock အသစ်ဝင်"; }

export default function PackagingBagStockPage() {
  const [date, setDate] = useState("");
  const [data, setData] = useState(null);
  const [form, setForm] = useState({ bagSize: BAG_RULES[0].bagSize, bags: "", note: "" });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  useEffect(() => { const queryDate = new URLSearchParams(window.location.search).get("date"); setDate(/^\d{4}-\d{2}-\d{2}$/.test(queryDate || "") ? queryDate : todayMyanmar()); }, []);
  const loadStock = useCallback(async () => {
    if (!date) return;
    setLoading(true); setError("");
    try { const response = await fetch(`/api/packaging-bag-stock?date=${encodeURIComponent(date)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "အိတ်ခွံလက်ကျန် ရယူ၍မရပါ။"); setData(body.data); } catch (loadError) { setError(loadError.message || "အိတ်ခွံလက်ကျန် ရယူ၍မရပါ။"); } finally { setLoading(false); }
  }, [date]);
  useEffect(() => { loadStock(); }, [loadStock]);

  const dailyUsed = useMemo(() => (data?.dailyUsed || []).filter((movement) => movement.movementDate === date), [data, date]);
  const dailyAdded = useMemo(() => (data?.dailyAdded || []).filter((movement) => movement.movementDate === date), [data, date]);

  async function saveStock(event) {
    event.preventDefault(); setSaving(true); setError(""); setMessage("");
    try { const response = await fetch("/api/packaging-bag-stock", { method: "POST", headers: actorHeaders({ "Content-Type": "application/json" }), body: JSON.stringify({ ...form, date }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "အိတ်ခွံ Stock ထည့်၍မရပါ။"); setMessage("အိတ်ခွံ Stock ထည့်သိမ်းပြီးပါပြီ။"); setForm({ ...form, bags: "", note: "" }); await loadStock(); } catch (saveError) { setError(saveError.message || "အိတ်ခွံ Stock ထည့်၍မရပါ။"); } finally { setSaving(false); }
  }

  const summary = data?.summary || [];
  return <main className="app-page-main"><div className="app-page-container app-page-surface space-y-4 pt-5 sm:pt-6">
    <section className="rounded-2xl border border-cyan-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold text-cyan-700">ထုပ်ပိုးအိတ်ခွံ အဝင်၊ သုံးစွဲမှုနှင့် လက်ကျန်</p><p className="mt-1 text-xs text-slate-500">Packaging Bag Report မှာတွက်ထားသော အသုံးပြုမှုကို အလိုအလျောက်နုတ်ပြီး Stock အသစ်ဝင်မှုနှင့် ပေါင်းပြထားပါသည်။</p></div><div className="flex flex-wrap justify-end gap-2"><div className="rounded-xl border border-cyan-200 bg-cyan-50 px-4 py-3 text-right"><p className="text-xs font-bold text-cyan-700">စက်ရုံ ထုပ်ပိုး အိတ်ခွံ လက်ကျန်</p><p className="mt-1 text-xl font-black text-cyan-950">{loading ? "ရယူနေသည်..." : `${formatNumber(data?.totalCurrentBags)} အိတ်`}</p></div><div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-right"><p className="text-xs font-bold text-rose-700">ယနေ့ သုံးစွဲပြီး</p><p className="mt-1 text-xl font-black text-rose-950">{loading ? "ရယူနေသည်..." : `${formatNumber(dailyUsed.reduce((sum, row) => sum + Math.abs(Number(row.quantityBottles || 0)), 0))} အိတ်`}</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-right"><p className="text-xs font-bold text-emerald-700">ယနေ့ အသစ်ထည့်</p><p className="mt-1 text-xl font-black text-emerald-950">{loading ? "ရယူနေသည်..." : `${formatNumber(dailyAdded.reduce((sum, row) => sum + Number(row.quantityBottles || 0), 0))} အိတ်`}</p></div></div></div><div className="mt-4 flex flex-wrap items-center gap-2"><label className="text-sm font-black text-cyan-900">Usage Date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-1 block min-h-10 rounded-lg border-2 border-cyan-200 bg-cyan-50 px-3 py-2 font-bold text-cyan-900" /></label>{[-1, 0, 1].map((delta) => { const value = shiftDate(todayMyanmar(), delta); const label = delta === -1 ? "မနေ့" : delta === 0 ? "ဒီနေ့" : "မနက်ဖြန်"; return <button key={label} type="button" onClick={() => setDate(value)} className={`mt-5 rounded-lg border px-3 py-2 text-sm font-black ${date === value ? "border-cyan-600 bg-cyan-600 text-white" : "border-cyan-200 bg-cyan-50 text-cyan-800"}`}>{label}</button>; })}</div></section>
    <section className="rounded-2xl border border-violet-200 bg-white p-4 shadow-sm sm:p-5"><h2 className="text-base font-black text-violet-900">အိတ်ခွံ အသစ်ဝင် Stock ထည့်ရန်</h2><p className="mt-1 text-xs text-slate-500">အပေါ်မှာ Packaging Bag Report မှာပြထားသော အိတ်အရွယ်အစားအတိုင်း Stock အသစ်ကို ထည့်ပါ။</p><form onSubmit={saveStock} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold text-slate-700">Stock ဝင်ရက်<input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-violet-200 px-2 text-sm font-bold" /></label><label className="text-xs font-bold text-slate-700">အိတ်အရွယ်အစား<select value={form.bagSize} onChange={(event) => setForm({ ...form, bagSize: event.target.value })} className="mt-1 h-10 w-full rounded-lg border border-violet-200 bg-white px-2 text-sm font-bold">{BAG_RULES.map((rule) => <option key={rule.bagSize} value={rule.bagSize}>{rule.bagSize} အိတ်</option>)}</select></label><label className="text-xs font-bold text-slate-700">အိတ်အရေအတွက်<input type="number" min="1" step="1" required value={form.bags} onChange={(event) => setForm({ ...form, bags: event.target.value })} className="mt-1 h-10 w-full rounded-lg border border-violet-200 px-2 text-center text-sm font-black" placeholder="ဥပမာ 80" /></label><label className="text-xs font-bold text-slate-700">မှတ်ချက်<input value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} className="mt-1 h-10 w-full rounded-lg border border-violet-200 px-2 text-sm" placeholder="အသစ်ရောက် / လက်ရှိစာရင်း" /></label><button disabled={saving} className="h-10 rounded-lg bg-violet-700 px-4 text-sm font-black text-white hover:bg-violet-800 disabled:opacity-50 sm:col-span-2 lg:col-span-4">{saving ? "သိမ်းနေသည်..." : "အိတ်ခွံ Stock ထည့်သိမ်းမည်"}</button></form>{message ? <p className="mt-3 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">{message}</p> : null}</section>
    {error ? <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 font-bold text-rose-700">{error}</div> : null}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-cyan-50 text-left text-xs font-black text-cyan-950"><tr><th className="px-4 py-3">အိတ်အရွယ်အစား</th><th className="px-4 py-3 text-right">အသစ်ဝင် စုစုပေါင်း</th><th className="px-4 py-3 text-right">အဟောင်းသုံးစွဲ စုစုပေါင်း</th><th className="px-4 py-3 text-right">လက်ကျန်</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan="4" className="px-4 py-8 text-center font-bold text-slate-500">အိတ်ခွံလက်ကျန် ရယူနေသည်...</td></tr> : summary.map((item) => <tr key={item.bagSize}><td className="px-4 py-3 font-black text-slate-900">{item.bagSize} အိတ်</td><td className="px-4 py-3 text-right font-bold text-emerald-700">+{formatNumber(item.addedBags)} အိတ်</td><td className="px-4 py-3 text-right font-bold text-rose-700">-{formatNumber(item.usedBags)} အိတ်</td><td className={`px-4 py-3 text-right text-base font-black ${item.systemCurrentBags < 0 ? "text-rose-700" : "text-cyan-900"}`}>{formatNumber(item.currentBags)} အိတ်</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-rose-200 bg-white p-4 shadow-sm"><h2 className="font-black text-rose-900">အဟောင်း သုံးစွဲမှု — {date}</h2><p className="mt-1 text-xs text-slate-500">Packaging Bag Report မှ အလိုအလျောက်နုတ်ထားသော မှတ်တမ်း</p><div className="mt-3 space-y-2">{dailyUsed.length ? dailyUsed.map((movement) => <div key={movement.id} className="flex items-center justify-between gap-3 rounded-xl bg-rose-50 p-3"><div><p className="font-black text-slate-900">{movement.productName}</p><p className="text-xs font-bold text-slate-500">{movement.note || movement.reason}</p></div><p className="text-right font-black text-rose-700">-{formatNumber(Math.abs(movement.quantityBottles || 0))} အိတ်</p></div>) : <p className="py-6 text-center font-bold text-slate-500">ဒီနေ့ အိတ်ခွံသုံးစွဲမှု မရှိသေးပါ။</p>}</div></section><section className="rounded-2xl border border-emerald-200 bg-white p-4 shadow-sm"><h2 className="font-black text-emerald-900">ယနေ့ အသစ်ထည့်ထားသော Stock</h2><div className="mt-3 space-y-2">{dailyAdded.length ? dailyAdded.map((movement) => <div key={movement.id} className="flex items-center justify-between gap-3 rounded-xl bg-emerald-50 p-3"><div><p className="font-black text-slate-900">{movement.productName}</p><p className="text-xs font-bold text-slate-500">{movement.note || movement.reason}</p></div><p className="text-right font-black text-emerald-700">+{formatNumber(movement.quantityBottles || 0)} အိတ်</p></div>) : <p className="py-6 text-center font-bold text-slate-500">ဒီနေ့ အသစ်ထည့်ထားသော Stock မရှိသေးပါ။</p>}</div></section></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black text-slate-900">အိတ်ခွံ Movement မှတ်တမ်း</h2><div className="mt-3 space-y-2">{(data?.movements || []).length ? data.movements.map((movement) => <div key={movement.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><p className="font-black text-slate-900">{movement.productName} · {movementLabel(movement)}</p><p className="text-xs font-bold text-slate-500">{movement.movementDate} · {movement.note || movement.reason}</p></div><p className={`text-right font-black ${Number(movement.quantityBottles || 0) < 0 ? "text-rose-700" : "text-emerald-700"}`}>{Number(movement.quantityBottles || 0) > 0 ? "+" : "−"}{formatNumber(Math.abs(movement.quantityBottles || 0))} အိတ်</p></div>) : <p className="py-6 text-center font-bold text-slate-500">Movement မှတ်တမ်း မရှိသေးပါ။</p>}</div></section>
  </div></main>;
}
