"use client";
import { useEffect, useMemo, useState } from "react";
const money = (v) => `${Number(v || 0).toLocaleString("en-US")} Ks`;
const initial = [
  ["ဆန်", "ဆန် ၉ အိတ်နှင့် ၈ ပြည်", 1359375],
  ["ဟင်းချက်ဆီ", "၂၅ ပိဿာ ၅၀သား", 499800],
  ["အသား", "အသား", 1817500],
  ["အသီးအရွက်နှင့် ဟင်းထဲထည့်သည့် အစာပလာဘိုး", "အသီးအရွက်နှင့် ဟင်းထဲထည့်သည့် အစာပလာဘိုး", 1713000],
];
export default function ExpensesPage() {
  const [rows, setRows] = useState([]); const [form, setForm] = useState({ expenseDate: "2026-08-31", category: "စားသောက်စာရိတ်", description: "", amount: "", note: "" }); const [error, setError] = useState("");
  async function load() { const res = await fetch("/api/expenses?month=2026-08"); const body = await res.json(); const existing = body.data || []; if (!existing.length) { const seeded = await Promise.all(initial.map(([category, description, amount]) => fetch("/api/expenses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expenseDate: "2026-08-31", category: "စားသောက်စာရိတ်", description, amount }) }).then((r) => r.json()).then((x) => x.data).catch(() => null))); setRows(seeded.filter(Boolean)); } else setRows(existing); }
  useEffect(() => { load().catch(() => setError("စာရင်းရယူ၍ မရပါ။")); }, []);
  const total = useMemo(() => rows.reduce((s, r) => s + Number(r.amount || 0), 0), [rows]);
  async function save(e) { e.preventDefault(); setError(""); const res = await fetch("/api/expenses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await res.json(); if (!res.ok) return setError(body.error || "သိမ်း၍ မရပါ။"); setRows((r) => [body.data, ...r]); setForm({ ...form, description: "", amount: "", note: "" }); }
  async function remove(id) { if (!confirm("ဖျက်မည်လား။")) return; await fetch(`/api/expenses?id=${id}`, { method: "DELETE" }); setRows((r) => r.filter((x) => x.id !== id)); }
  return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-5xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold text-emerald-700">စာရင်းစီမံခန့်ခွဲမှု</p><h1 className="text-3xl font-black">အသုံးစားရိတ်</h1><p className="mt-1 text-sm text-slate-500">စားသောက်စာရိတ်နှင့် အခြားအသုံးစရိတ်များကို မှတ်တမ်းတင်ရန်</p></div><a href="/" className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">မူလစာမျက်နှာ</a></div>
    <section className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">အသုံးစားရိတ် ထည့်ရန်</h2><form onSubmit={save} className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm font-bold">ရက်စွဲ<input type="date" value={form.expenseDate} onChange={e => setForm({...form, expenseDate:e.target.value})} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold">အမျိုးအစား<input value={form.category} onChange={e => setForm({...form, category:e.target.value})} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold">အသုံးစရိတ်အမည်<input required value={form.description} onChange={e => setForm({...form, description:e.target.value})} placeholder="ဥပမာ - ဆန်" className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold">ငွေပမာဏ (Ks)<input required inputMode="numeric" value={form.amount} onChange={e => setForm({...form, amount:e.target.value.replace(/[^0-9,]/g, "")})} placeholder="1,359,375" className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold md:col-span-2">မှတ်ချက်<textarea value={form.note} onChange={e => setForm({...form, note:e.target.value})} className="mt-1 w-full rounded-xl border p-3" rows="2" /></label><button className="rounded-xl bg-emerald-600 px-5 py-3 font-black text-white md:col-span-2">သိမ်းမည်</button></form>{error && <p className="mt-3 rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>}</section>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-black">ဩဂုတ်လ စားသောက်စာရိတ်</h2><div className="text-right"><p className="text-xs text-slate-500">စုစုပေါင်း</p><p className="text-2xl font-black text-emerald-700">{money(total)}</p></div></div><div className="mt-4 space-y-2">{rows.map((r) => <div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><p className="font-black">{r.description}</p><p className="text-xs text-slate-500">{r.category} · {r.expenseDate || "ဩဂုတ်လ"}</p></div><div className="flex items-center gap-3"><b className="text-emerald-700">{money(r.amount)}</b><button onClick={() => remove(r.id)} className="text-xs font-bold text-rose-600">ဖျက်</button></div></div>)}</div><div className="mt-5 rounded-xl bg-emerald-50 p-4 text-center font-black text-emerald-900">စာရင်းအရ စုစုပေါင်း — {money(total)}</div></section></div></main>;
}
